-- 测试数据库表结构
-- 物流订单表
CREATE TABLE IF NOT EXISTS logistics_orders (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    logistics_order_no VARCHAR(50) NOT NULL COMMENT '物流订单号（系统生成）',
    business_order_id BIGINT COMMENT '关联的业务订单ID',
    business_order_no VARCHAR(50) COMMENT '关联的业务订单号',
    logistics_type TINYINT NOT NULL COMMENT '物流类型：1-标准快递，2-特快专递，3-经济快递，4-国际快递，5-海运，6-空运，7-陆运，8-同城配送',
    status TINYINT NOT NULL DEFAULT 0 COMMENT '物流状态：0-待处理，1-已创建，2-已揽收，3-运输中，4-到达目的地，5-派送中，6-已签收，7-异常，8-退回，9-已取消',
    provider_name VARCHAR(100) NOT NULL COMMENT '物流服务商名称',
    provider_code VARCHAR(50) NOT NULL COMMENT '物流服务商代码',
    tracking_number VARCHAR(100) COMMENT '运单号',
    sender_info JSON COMMENT '发件人信息（JSON格式存储）',
    recipient_info JSON COMMENT '收件人信息（JSON格式存储）',
    package_info JSON COMMENT '包裹信息（JSON格式存储）',
    shipping_cost DECIMAL(10,2) COMMENT '物流费用',
    currency VARCHAR(10) DEFAULT 'CNY' COMMENT '币种',
    estimated_ship_time DATETIME COMMENT '预计发货时间',
    actual_ship_time DATETIME COMMENT '实际发货时间',
    estimated_delivery_time DATETIME COMMENT '预计送达时间',
    actual_delivery_time DATETIME COMMENT '实际送达时间',
    service_level VARCHAR(50) COMMENT '物流服务等级',
    require_signature TINYINT(1) DEFAULT 0 COMMENT '是否需要签收：0-否，1-是',
    insured TINYINT(1) DEFAULT 0 COMMENT '是否保价：0-否，1-是',
    insured_value DECIMAL(10,2) COMMENT '保价金额',
    remarks TEXT COMMENT '备注信息',
    extend_info JSON COMMENT '扩展信息（JSON格式存储）',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    create_by BIGINT COMMENT '创建人ID',
    update_by BIGINT COMMENT '更新人ID',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标志：0-未删除，1-已删除',
    version INT NOT NULL DEFAULT 1 COMMENT '版本号（用于乐观锁）',
    PRIMARY KEY (id),
    UNIQUE KEY uk_logistics_order_no (logistics_order_no),
    KEY idx_business_order_id (business_order_id),
    KEY idx_business_order_no (business_order_no),
    KEY idx_tracking_number (tracking_number),
    KEY idx_provider_code (provider_code),
    KEY idx_status (status),
    KEY idx_create_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='物流订单表';

-- 面单信息表
CREATE TABLE IF NOT EXISTS shipping_labels (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    logistics_order_id BIGINT NOT NULL COMMENT '关联的物流订单ID',
    label_number VARCHAR(50) NOT NULL COMMENT '面单编号',
    tracking_number VARCHAR(100) NOT NULL COMMENT '运单号',
    status TINYINT NOT NULL DEFAULT 0 COMMENT '面单状态：0-待生成，1-已生成，2-已打印，3-已使用，4-已作废',
    format TINYINT NOT NULL DEFAULT 1 COMMENT '面单格式：1-PDF，2-PNG，3-JPG，4-ZPL，5-EPL',
    label_content LONGTEXT COMMENT '面单内容（Base64编码的PDF或图片）',
    label_url VARCHAR(500) COMMENT '面单URL（如果存储在文件服务器）',
    label_size VARCHAR(20) COMMENT '面单尺寸信息',
    print_count INT NOT NULL DEFAULT 0 COMMENT '打印次数',
    printed TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否已打印：0-否，1-是',
    generate_params JSON COMMENT '面单生成参数（JSON格式存储）',
    remarks TEXT COMMENT '备注信息',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    create_by BIGINT COMMENT '创建人ID',
    update_by BIGINT COMMENT '更新人ID',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标志：0-未删除，1-已删除',
    version INT NOT NULL DEFAULT 1 COMMENT '版本号（用于乐观锁）',
    PRIMARY KEY (id),
    UNIQUE KEY uk_label_number (label_number),
    KEY idx_logistics_order_id (logistics_order_id),
    KEY idx_tracking_number (tracking_number),
    KEY idx_status (status),
    KEY idx_create_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='面单信息表';

-- 地址信息表
CREATE TABLE IF NOT EXISTS addresses (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    address_type TINYINT NOT NULL COMMENT '地址类型：1-发件人地址，2-收件人地址，3-退货地址，4-仓库地址，5-门店地址',
    contact_name VARCHAR(100) NOT NULL COMMENT '联系人姓名',
    contact_phone VARCHAR(20) COMMENT '联系电话',
    email VARCHAR(100) COMMENT '邮箱地址',
    company_name VARCHAR(200) COMMENT '公司名称',
    country_code VARCHAR(10) NOT NULL COMMENT '国家代码',
    country_name VARCHAR(100) NOT NULL COMMENT '国家名称',
    state_code VARCHAR(10) COMMENT '省/州代码',
    state_name VARCHAR(100) COMMENT '省/州名称',
    city_code VARCHAR(10) COMMENT '城市代码',
    city_name VARCHAR(100) NOT NULL COMMENT '城市名称',
    district_code VARCHAR(10) COMMENT '区/县代码',
    district_name VARCHAR(100) COMMENT '区/县名称',
    detail_address VARCHAR(500) NOT NULL COMMENT '详细地址',
    postal_code VARCHAR(20) COMMENT '邮政编码',
    address_label VARCHAR(50) COMMENT '地址标签（如：家、公司、其他）',
    is_default TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否为默认地址：0-否，1-是',
    verified TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否已验证：0-否，1-是',
    latitude DECIMAL(10,7) COMMENT '纬度',
    longitude DECIMAL(10,7) COMMENT '经度',
    remarks TEXT COMMENT '备注信息',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    create_by BIGINT COMMENT '创建人ID',
    update_by BIGINT COMMENT '更新人ID',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标志：0-未删除，1-已删除',
    version INT NOT NULL DEFAULT 1 COMMENT '版本号（用于乐观锁）',
    PRIMARY KEY (id),
    KEY idx_address_type (address_type),
    KEY idx_contact_name (contact_name),
    KEY idx_country_code (country_code),
    KEY idx_city_name (city_name),
    KEY idx_is_default (is_default),
    KEY idx_create_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='地址信息表';